<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="1" passed="0" failed="1" skipped="0">
  <reporter-output>
    <line>
      <![CDATA[---Database connection established---]]>
    </line>
    <line>
      <![CDATA[Contacts page displayed successfully]]>
    </line>
    <line>
      <![CDATA[Create contacts page displayed successfully]]>
    </line>
    <line>
      <![CDATA[Contacts info page displayed successfully]]>
    </line>
    <line>
      <![CDATA[Contacts created successfully --- Testcase Passed]]>
    </line>
    <line>
      <![CDATA[---Disconnecting from DataBase---]]>
    </line>
  </reporter-output>
  <suite started-at="2024-03-23T10:00:53 IST" name="Default suite" finished-at="2024-03-23T10:01:51 IST" duration-ms="57505">
    <groups>
      <group name="smoke">
        <method signature="toCreateContact1Test.toCreateContactTest_001()[pri:0, instance:vtiger.contactTests.toCreateContact1Test@4f209819]" name="toCreateContactTest_001" class="vtiger.contactTests.toCreateContact1Test"/>
      </group> <!-- smoke -->
    </groups>
    <test started-at="2024-03-23T10:00:53 IST" name="Default test" finished-at="2024-03-23T10:01:51 IST" duration-ms="57505">
      <class name="vtiger.contactTests.toCreateContact1Test">
        <test-method is-config="true" signature="beforeSuiteConfiguration()[pri:0, instance:vtiger.contactTests.toCreateContact1Test@4f209819]" started-at="2024-03-23T10:00:53 IST" name="beforeSuiteConfiguration" finished-at="2024-03-23T10:00:53 IST" duration-ms="15" status="PASS">
          <reporter-output>
            <line>
              <![CDATA[---Database connection established---]]>
            </line>
          </reporter-output>
        </test-method> <!-- beforeSuiteConfiguration -->
        <test-method is-config="true" signature="beforeClassConfiguration()[pri:0, instance:vtiger.contactTests.toCreateContact1Test@4f209819]" started-at="2024-03-23T10:00:54 IST" name="beforeClassConfiguration" finished-at="2024-03-23T10:01:10 IST" duration-ms="15988" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeClassConfiguration -->
        <test-method is-config="true" signature="beforeMethodConfiguration()[pri:0, instance:vtiger.contactTests.toCreateContact1Test@4f209819]" started-at="2024-03-23T10:01:10 IST" name="beforeMethodConfiguration" finished-at="2024-03-23T10:01:24 IST" duration-ms="14559" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeMethodConfiguration -->
        <test-method signature="toCreateContactTest_001()[pri:0, instance:vtiger.contactTests.toCreateContact1Test@4f209819]" started-at="2024-03-23T10:01:24 IST" name="toCreateContactTest_001" finished-at="2024-03-23T10:01:47 IST" duration-ms="22246" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [false] but found [true]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [false] but found [true]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertFalse(Assert.java:67)
at org.testng.Assert.assertFalse(Assert.java:77)
at vtiger.contactTests.toCreateContact1Test.toCreateContactTest_001(toCreateContact1Test.java:55)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:599)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:174)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:822)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:147)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:764)
at org.testng.TestRunner.run(TestRunner.java:585)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1218)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
at org.testng.TestNG.runSuites(TestNG.java:1069)
at org.testng.TestNG.run(TestNG.java:1037)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
            <line>
              <![CDATA[Contacts page displayed successfully]]>
            </line>
            <line>
              <![CDATA[Create contacts page displayed successfully]]>
            </line>
            <line>
              <![CDATA[Contacts info page displayed successfully]]>
            </line>
            <line>
              <![CDATA[Contacts created successfully --- Testcase Passed]]>
            </line>
          </reporter-output>
        </test-method> <!-- toCreateContactTest_001 -->
        <test-method is-config="true" signature="afterMethodConfiguration()[pri:0, instance:vtiger.contactTests.toCreateContact1Test@4f209819]" started-at="2024-03-23T10:01:47 IST" name="afterMethodConfiguration" finished-at="2024-03-23T10:01:49 IST" duration-ms="2173" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterMethodConfiguration -->
        <test-method is-config="true" signature="afterClassConfiguration()[pri:0, instance:vtiger.contactTests.toCreateContact1Test@4f209819]" started-at="2024-03-23T10:01:49 IST" name="afterClassConfiguration" finished-at="2024-03-23T10:01:51 IST" duration-ms="1628" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterClassConfiguration -->
        <test-method is-config="true" signature="afterSuiteConfiguration()[pri:0, instance:vtiger.contactTests.toCreateContact1Test@4f209819]" started-at="2024-03-23T10:01:52 IST" name="afterSuiteConfiguration" finished-at="2024-03-23T10:01:52 IST" duration-ms="3" status="PASS">
          <reporter-output>
            <line>
              <![CDATA[---Disconnecting from DataBase---]]>
            </line>
          </reporter-output>
        </test-method> <!-- afterSuiteConfiguration -->
      </class> <!-- vtiger.contactTests.toCreateContact1Test -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
